=== svoboda-rabsvto/linterhub-cli/src/hub/.schema/engine.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "This document describes the engine definition",
    "description": "The meta information of engine",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "The engine name"
        },
        "description": {
            "type": "string",
            "description": "The engine description"
        },
        "url": {
            "type": "string",
            "description": "The engine url or homepage",
            "format": "uri"
        },
        "version": {
            "description": "The engine version (expected)",
            "type": "object",
            "properties": {
                "package": {
                    "type": "string",
                    "description": "Package version"
                },
                "local": {
                    "type": "string",
                    "description": "Local version"
                }
            }
        },
        "languages": {
            "type": "array",
            "description": "The list of supported languages",
            "items": {
                "type": "string",
                "enum": [
                    "coffeescript",
                    "css",
                    "html",
                    "javascript",
                    "json",
                    "jsx",
                    "sass",
                    "typescript"
                ]
            }
        },
        "extensions": {
            "type": "array",
            "description": "Common file extensions parsed by engine",
            "items": {
                "type": "string"
            }
        },
        "license": {
            "type": "string",
            "description": "The engine license",
            "enum": [
                "Unknown",
                "AGPL-3.0",
                "Apache-2.0",
                "MIT"
            ]
        },
        "requirements": {
            "type": "array",
            "description": "The engine requirements",
            "items": {
                "$ref": "#/definitions/requirement"
            }
        },
        "areas": {
            "type": "array",
            "description": "The engine areas",
            "items": {
                "type": "string",
                "enum": [
                    "code simplification",
                    "commented code",
                    "complexity",
                    "documentation",
                    "duplication",
                    "formatting",
                    "grammar",
                    "memory leak",
                    "security",
                    "simplification",
                    "smell",
                    "spelling",
                    "syntax",
                    "undefined element",
                    "unreachable code",
                    "unused code"
                ]
            }
        },
        "prefix": {
            "type": "string",
            "description": "Prefix in terminal (normally engine name)"
        },
        "postfix": {
            "type": "string",
            "description": "Postfix in terminal (normaly post processor)"
        },
        "optionsDelimiter": {
            "type": "string",
            "description": "Delimiter for options (space by default)",
            "default": " "
        },
        "successCode": {
            "type": "integer",
            "description": "Success exit code"
        },
        "active": {
            "type": "boolean",
            "description": "A value indicating whether linter is active",
            "default": true
        },
        "defaults": {
            "type": "object",
            "description": "The default configuration of engine. This property is specific for each engine"
        }
    },
    "required": [
        "name",
        "description",
        "languages",
        "license",
        "areas"
    ],
    "definitions": {
        "requirement": {
            "type": "object",
            "description": "The engine dependency",
            "properties": {
                "manager": {
                    "type": "string",
                    "description": "The manager for dependency",
                    "enum": [
                        "system",
                        "url",
                        "composer",
                        "gem",
                        "npm",
                        "pip"
                    ]
                },
                "package": {
                    "type": "string",
                    "description": "The package name"
                }
            }
        }
    }
}

=== svoboda-rabsvto/linterhub-cli/src/cli/linterhub/csslint/linter.json
{
  "$schema": "./../linter.schema.json",
  "name": "csslint",
  "description": "Automated linting of Cascading Stylesheets",
  "url": "http://csslint.net",
  "languages": [ "css" ],
  "extensions": [ "*.css" ],
  "license": "MIT",
  "areas": [ "syntax", "code simplification" ],
  "requirements": [
    {
      "manager": "system",
      "package": "npm"
    },
    {
      "manager": "npm",
      "package": "csslint"
    }
  ],
  "version": {
    "local": "v1.0.4",
    "package": "1.0.4"
  },
  "postfix": " | node file://{schema}/csslint/reporter.js",
  "prefix": "node file://{schema}/csslint/prefix.js ",
  "optionsDelimiter": "=",
  "defaults": {
    "": "./",
    "--format": "compact"
  }
}

=== svoboda-rabsvto/linterhub-cli/src/cli/linterhub/standard/linter.json
{
  "$schema": "./../linter.schema.json",
  "name": "standard",
  "description": "JavaScript Standard Style",
  "url": "http://standardjs.com",
  "languages": [ "javascript" ],
  "extensions": [ "*.js" ],
  "license": "MIT",
  "areas": [ "syntax" ],
  "requirements": [
    {
      "manager": "system",
      "package": "npm"
    },
    {
      "manager": "npm",
      "package": "standard"
    }
  ],
  "version": {
    "local": "10.0.2",
    "package": "10.0.2"
  },
  "postfix": " | node file://{schema}/standard/reporter.js",
  "defaults": {
    "--verbose": null,
    "": "**/**/*.js"
  }
}

=== svoboda-rabsvto/linterhub-cli/src/hub/stylelint/engine.json
{
    "$schema": "./../.schema/engine.json",
    "name": "stylelint",
    "description": "A mighty, modern CSS linter that helps you enforce consistent conventions and avoid errors in your stylesheets.",
    "url": "https://stylelint.io/",
    "languages": [
        "css"
    ],
    "extensions": [
        "*.css",
        "*.scss",
        "*.less",
        "*.sss"
    ],
    "license": "MIT",
    "areas": [
        "simplification",
        "syntax",
        "formatting"
    ],
    "requirements": [
        {
            "manager": "system",
            "package": "npm"
        },
        {
            "manager": "npm",
            "package": "stylelint"
        }
    ],
    "version": {
        "local": "7.11.1",
        "package": "7.11.1"
    },
    "defaults": {
        "": "**/**/*.*",
        "--custom-formatter": "file://{schema}/stylelint/reporter.js",
        "--config": "file://{schema}/stylelint/.stylelintrc"
    }
}

=== svoboda-rabsvto/linterhub-cli/src/hub/tslint/engine.json
{
    "$schema": "./../.schema/engine.json",
    "name": "tslint",
    "description": "An extensible linter for the TypeScript language.",
    "url": "https://palantir.github.io/tslint/",
    "languages": [
        "typescript"
    ],
    "extensions": [
        "*.ts"
    ],
    "license": "Apache-2.0",
    "areas": [
        "simplification",
        "syntax",
        "formatting",
        "complexity",
        "unused code"
    ],
    "requirements": [
        {
            "manager": "system",
            "package": "npm"
        },
        {
            "manager": "npm",
            "package": "typescript"
        },
        {
            "manager": "npm",
            "package": "tslint"
        }
    ],
    "postfix": " | node file://{schema}/tslint/reporter.js",
    "version": {
        "local": "5.4.3",
        "package": "5.4.3"
    },
    "defaults": {
        "": "**/**/*.ts",
        "--format": "verbose",
        "--config": "file://{schema}/tslint/tslint.json"
    }
}
