=== svoboda-rabsvto/linterhub-cli/src/hub/.schema/engine.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "This document describes the engine definition",
    "description": "The meta information of engine",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "The engine name"
        },
        "description": {
            "type": "string",
            "description": "The engine description"
        },
        "url": {
            "type": "string",
            "description": "The engine url or homepage",
            "format": "uri"
        },
        "version": {
            "description": "The engine version (expected)",
            "type": "object",
            "properties": {
                "package": {
                    "type": "string",
                    "description": "Package version"
                },
                "local": {
                    "type": "string",
                    "description": "Local version"
                }
            }
        },
        "languages": {
            "type": "array",
            "description": "The list of supported languages",
            "items": {
                "type": "string",
                "enum": [
                    "coffeescript",
                    "css",
                    "html",
                    "javascript",
                    "json",
                    "jsx",
                    "sass",
                    "typescript"
                ]
            }
        },
        "extensions": {
            "type": "array",
            "description": "Common file extensions parsed by engine",
            "items": {
                "type": "string"
            }
        },
        "license": {
            "type": "string",
            "description": "The engine license",
            "enum": [
                "Unknown",
                "AGPL-3.0",
                "Apache-2.0",
                "MIT"
            ]
        },
        "requirements": {
            "type": "array",
            "description": "The engine requirements",
            "items": {
                "$ref": "#/definitions/requirement"
            }
        },
        "areas": {
            "type": "array",
            "description": "The engine areas",
            "items": {
                "type": "string",
                "enum": [
                    "code simplification",
                    "commented code",
                    "complexity",
                    "documentation",
                    "duplication",
                    "formatting",
                    "grammar",
                    "memory leak",
                    "security",
                    "simplification",
                    "smell",
                    "spelling",
                    "syntax",
                    "undefined element",
                    "unreachable code",
                    "unused code"
                ]
            }
        },
        "prefix": {
            "type": "string",
            "description": "Prefix in terminal (normally engine name)"
        },
        "postfix": {
            "type": "string",
            "description": "Postfix in terminal (normaly post processor)"
        },
        "optionsDelimiter": {
            "type": "string",
            "description": "Delimiter for options (space by default)",
            "default": " "
        },
        "successCode": {
            "type": "integer",
            "description": "Success exit code"
        },
        "active": {
            "type": "boolean",
            "description": "A value indicating whether linter is active",
            "default": true
        },
        "defaults": {
            "type": "object",
            "description": "The default configuration of engine. This property is specific for each engine"
        }
    },
    "required": [
        "name",
        "description",
        "languages",
        "license",
        "areas"
    ],
    "definitions": {
        "requirement": {
            "type": "object",
            "description": "The engine dependency",
            "properties": {
                "manager": {
                    "type": "string",
                    "description": "The manager for dependency",
                    "enum": [
                        "system",
                        "url",
                        "composer",
                        "gem",
                        "npm",
                        "pip"
                    ]
                },
                "package": {
                    "type": "string",
                    "description": "The package name"
                }
            }
        }
    }
}

=== svoboda-rabsvto/linterhub-cli/src/cli/linterhub/jshint/linter.json
{
    "$schema": "./../linter.schema.json",
    "name": "jshint",
    "description": "JSHint is a tool that helps to detect errors and potential problems in your JavaScript code",
    "url": "http://jshint.com",
    "languages": [ "javascript" ],
    "extensions": [ "*.js" ],
    "license": "MIT",
    "areas": [ "syntax", "formatting", "complexity", "unused code" ],
    "requirements": [ 
        { "manager": "system", "package": "npm" },
        { "manager": "npm", "package": "jshint" }
    ],
    "version": {
        "local": "jshint v2.9.4",
        "package": "2.9.4"
    },
  "defaults": {
    "": "./",
    "--reporter": "file://{schema}/jshint/reporter.js"
  }
}

=== svoboda-rabsvto/linterhub-cli/src/cli/linterhub/jslint/linter.json
{
    "$schema": "./../linter.schema.json",
    "name": "jslint",
    "description": "The JavaScript Code Quality Tool.",
    "url": "http://jslint.com",
    "languages": [
        "javascript"
    ],
    "extensions": [
        "*.js"
    ],
    "license": "MIT",
    "areas": [
        "syntax",
        "formatting",
        "complexity",
        "unused code"
    ],
    "requirements": [
        {
            "manager": "system",
            "package": "npm"
        },
        {
            "manager": "npm",
            "package": "jslint"
        }
    ],
    "postfix": " | node file://{schema}/jslint/reporter.js",
    "version": {
        "local": "node-jslint version: 0.10.3  JSLint edition 2013-08-26",
        "package": "0.10.3"
    },
    "defaults": {
        "": "**/**/*.js",
        "--json": ""
    }
}

=== svoboda-rabsvto/linterhub-cli/src/cli/linterhub/coffeelint/linter.json
{
    "$schema": "./../linter.schema.json",
    "name": "coffeelint",
    "description": "CoffeeLint is a style checker that helps keep CoffeeScript code clean and consistent",
    "url": "http://www.coffeelint.org",
    "languages": [ "coffeescript" ],
    "extensions": [ "*.coffee" ],
    "license": "MIT",
    "areas": [ "syntax", "formatting", "smell", "complexity", "duplication" ],
    "requirements": [ 
        { "manager": "system", "package": "npm" },
        { "manager": "npm", "package": "coffeelint" }
    ],
    "version": {
        "local": "1.16.0",
        "package": "1.16.0"
    },
    "defaults": {
        "--reporter": "file://{schema}/coffeelint/reporter.coffee",
        "": "./"
    }
}

=== svoboda-rabsvto/linterhub-cli/src/cli/linterhub/eslint/linter.json
{
    "$schema": "./../linter.schema.json",
    "name": "eslint",
    "description": "A fully pluggable tool for identifying and reporting on patterns in JavaScript",
    "url": "http://eslint.org",
    "languages": [ "javascript", "jsx" ],
    "extensions": [ "*.js" ],
    "license": "MIT",
    "areas": [ "syntax" ],
    "requirements": [ 
        { "manager": "system", "package": "npm" },
        { "manager": "npm", "package": "eslint" }
    ],
    "version": {
        "local": "v3.19.0",
        "package": "3.19.0"
    },
    "defaults": {
        "--format": "file://{schema}/eslint/reporter.js",
        "--config": "file://{schema}/eslint/.eslintrc.js",
        "": "**/**/*.js"
    }
}

=== svoboda-rabsvto/linterhub-cli/src/cli/linterhub/colorguard/linter.json
{
    "$schema": "./../linter.schema.json",
    "name": "colorguard",
    "description": "CSS Colorguard helps you maintain the color set that you want, and warns you when colors you've added are too similar to ones that already exist.",
    "url": "https://github.com/SlexAxton/css-colorguard",
    "languages": [
        "css"
    ],
    "extensions": [
        "*.css"
    ],
    "license": "MIT",
    "areas": [
        "formatting"
    ],
    "requirements": [
        {
            "manager": "system",
            "package": "npm"
        },
        {
            "manager": "npm",
            "package": "colorguard"
        }
    ],
    "postfix": " node file://{schema}/colorguard/reporter.js",
    "prefix": "node file://{schema}/colorguard/prefix.js ",
    "version": {
        "package": "1.2.0"
    },
    "defaults": {
        "--file": null,
        "": "*"
    }
}

=== svoboda-rabsvto/linterhub-cli/src/cli/linterhub/jsonlint/linter.json
{
    "$schema": "./../linter.schema.json",
    "name": "jsonlint",
    "description": "A pure JavaScript version of the service provided at jsonlint.com.",
    "url": "https://github.com/zaach/jsonlint",
    "languages": [
        "json"
    ],
    "extensions": [
        "*.json"
    ],
    "license": "MIT",
    "areas": [
        "syntax",
        "formatting"
    ],
    "requirements": [
        {
            "manager": "system",
            "package": "npm"
        },
        {
            "manager": "npm",
            "package": "jsonlint"
        }
    ],
    "postfix": " | node file://{schema}/jsonlint/reporter.js",
    "prefix": "node file://{schema}/jsonlint/prefix.js ",
    "version": {
        "local": "1.6.2",
        "package": "1.6.2"
    },
    "defaults": {
        "": "*",
        "--quiet": null,
        "--compact": null
    }
}

=== svoboda-rabsvto/linterhub-cli/src/cli/linterhub/sass-lint/linter.json
{
  "$schema": "./../linter.schema.json",
  "name": "sass-lint",
  "description": "A Node-only Sass linter for both sass and scss syntax!",
  "url": "https://github.com/sasstools/sass-lint",
  "languages": [ "sass" ],
  "extensions": [ "*.sass", "*.scss" ],
  "license": "MIT",
  "areas": [ "syntax", "formatting" ],
  "requirements": [
    {
      "manager": "system",
      "package": "npm"
    },
    {
      "manager": "npm",
      "package": "sass-lint"
    }
  ],
  "version": {
    "local": "1.10.2",
    "package": "1.10.2"
  },
  "postfix": " | node file://{schema}/sass-lint/reporter.js",
  "defaults": {
    "": "*",
    "--verbose": null,
    "--format": "json"
  }
}

=== svoboda-rabsvto/linterhub-cli/src/hub/htmlhint/engine.json
{
    "$schema": "./../.schema/engine.json",
    "name": "htmlhint",
    "description": "HTMLHint is a Static Code Analysis Tool for HTML",
    "url": "http://htmlhint.com",
    "languages": [
        "html"
    ],
    "extensions": [
        "*.html"
    ],
    "license": "MIT",
    "areas": [
        "syntax"
    ],
    "requirements": [
        {
            "manager": "system",
            "package": "npm"
        },
        {
            "manager": "npm",
            "package": "htmlhint"
        }
    ],
    "version": {
        "local": "0.9.13",
        "package": "0.9.13"
    },
    "postfix": " | node file://{schema}/htmlhint/reporter.js",
    "defaults": {
        "": "**/**/*.html",
        "--format": "json"
    }
}
